
define(function () {
  return {
    i18n: {
      pt_BR: {
        source: 'Fonte',
        medical_imaging_on_the_web: 'Imagens Médicas na Web \uD83D\uDC89',
        who_am_i: 'Quem és tu, mancebo?',
        human_30y_plus: 'Humano que passou dos 30...',
        father_of_a_boy: 'Pai de um garotinho maravilhoso!',
        husband_of_a_beautiful_wife: 'Marido de uma bela esposa!',
        works_with_web_for_10y_plus: 'Trabalha com Web há mais de 10 anos...',
        works_with_medica_imaging_for_3y_plus: '... e com imagens médicas há mais de 3 anos!',
        motivation: 'Motivação',
        advertise_open_source_medical_imaging_projects: 'Divulgar projetos open-source da área',
        draw_community_attention_to_medical_imaging: 'Despertar interesse da comunidade',
        make_the_subject_less_obscure: 'Tornar o assunto menos obscuro',
        organization: 'Organização',
        definition_of_medical_images: 'Definição',
        history_of_medical_images: 'História',
        existing_open_source_projects_on_medical_imaging: 'Projetos',
        what_is_medical_imaging: 'O que são imagens médicas?',
        medical_imaging_definition: 'Toda tecnologia de imagem que pode ser utilizada para realização de diagnósticos.',
        what_some_think_it_is: 'Alguns imaginam que seja isso:',
        or_this: '... ou isso:',
        what_medical_images_actually_are: 'Na verdade é isso:',
        another_examplo_of_medical_imaging: '... e um outro exemplo:',
        what_is_different: 'O que exatamente é diferente?',
        almost_everything_is_different: 'Quase tudo:',
        acquisition_method: 'Método de aquisição',
        data_organization: 'Estrutura de dados',
        file_format: 'Formato de arquivo',
        among_other_things: 'Entre outros...',
        what_regular_images_are: 'Imagens comuns são...',
        regular_images_are_projections_of_visible_light: '... projeções bidimensionais da luz visível:',
        regular_images_were_designed_to_be_simple_light_scans: 'Simples matrizes de pontos/cores',
        regular_images_depend_on_light: 'Dependem da luz visível',
        regular_images_very_limited_overall: 'No geral, muito limitadas',
        regular_image_sensor: 'Sensor de imagem comum:',
        how_different_are_medical_images: 'Imagens médicas, por sua vez...',
        medical_images_can_be_generated_from_various_phenomena: '... podem ser geradas de diferentes fenômenos.',
        medical_images_dont_depend_exclusively_on_light: 'Não dependem exclusivamente de luz!',
        medical_images_were_designed_to_store_context: 'Projetadas para armazenar contexto...',
        almost_unlimited_context: '... muito contexto!',
        highly_standardized: 'Fortemente padronizadas',
        medical_imaging_device: 'Modalidade',
        modalities: 'Modalidades',
        radiography: 'Radiografia',
        magnetic_resonance_imaging: 'Ressonância Magnética',
        nuclear_medicine: 'Medicina Nuclear',
        tomography: 'Tomografia',
        ultrasound: 'Ultrassonografia',
        analogy: 'Analogia!',
        everything_the_light_touches: 'Tudo isso que a luz toca, são as imagens comuns...',
        what_about_that_shadowy_place: 'E aquele lugar escuro, lá?',
        that_shadowy_place_is_medical_images: 'São as imagens médicas...',
        a_bit_of_history: 'Um pouco de história...',
        hand_with_rings: 'Mão com anéis: Primeiro Raio-X "médico" da esposa de Wilhelm Röntgen',
        xrays_more_more_than_40y_later: 'Mais de 40 anos depois...'
      },
      en_US: {
        hand_with_rings: 'Hand with Rings: print of Wilhelm Röntgen\'s first "medical" X-ray, of his wife\'s hand'
      }
    }
  }
});
